# Deployment -------> It consists of #Pod and #Replica-set both........

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      - containers:
          - name: nginx-container
            image: nginx:latest
            ports:
              - containerPort: 80  #container port or the port to which the traffic will be forwarded to on the pods      
                protocol: "TCP"


---


# NodePort Service

apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-svc
spec:
  type: NodePort
  ports:
    - targetPort: 80   #container port or the port to which the traffic will be forwarded to on the pods
      port: 80  #service port or the port on which the service will listen ------> yaha service bole to actual application i.e. here is nginx
      nodePort: 30000  #nodePort service Port
  selector:
    app: nginx    

---

# ClusterIP

apiVersion: v1
kind: Servive
metadata:
  name: nginx-backend-svc
spec:
  type: ClusterIP
  ports:
    - targetPort: 80  #container port or the port to which the traffic will be forwarded to on the pods
      port: 80  #service port or the port on which the service will listen ------> yaha service bole to actual application i.e. here is nginx   
  selector:
    app: nginx     

---

# LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80  #container port or the port to which the traffic will be forwarded to on the pods
      port: 80  #service port or the port on which the service will listen ------> yaha service bole to actual application i.e. here is nginx        
      nodePort: 30000  #nodePort service Port
  selector:
    app: nginx    
   
    






